# fly.toml app configuration file generated for telegram-youtube-bot on 2023-08-09T22:43:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telegram-youtube-bot"
primary_region = "gru"

[http_service]
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
